services:
#    stand_app.example:
#        class: StandAppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    stand_app.admin.membership_category:
        class: StandAppBundle\Admin\MembershipCategoryAdmin
        arguments: [~, StandAppBundle\Entity\MembershipCategory, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: MembershipCategory }
