<?php

namespace StandAppBundle\Repository;

/**
 * MembershipCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
