<?php

namespace StandAppBundle\Repository;

/**
 * PaymentModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentModeRepository extends \Doctrine\ORM\EntityRepository
{
}
